config/routes.rb
Rails.application.routes.draw do
  root to: 'event#index'
  get 'static_pages/secret'
  devise_for :users
  resources :event
  resources :users,  only: [:show] do
    resources :avatars, only: [:create]
  end
  resources :charges
  resources :avatars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :noob, class_name: "User"
  belongs_to :event







end

app/models/event.rb
class Event < ApplicationRecord
    has_one_attached :avatar
  has_many :attendances
  has_many :noob, through: :attendances, class_name: "User"
  belongs_to :administrator, class_name: "User"


  validates :start_date,
        presence: true, inclusion: { in: (Date.today..Date.today+50.years) }



  #validates :duration,
 #numericality: { only_integer: true }, if:  :is_multiple_5?

  #def is_multiple_5?
  #if self.duration % 5 != 0
  #  errors.add(:duration, "La durée doit être un multiple de 5")
  #end
#  end

  validates :title,
  presence: true, length: { minimum: 5, maximum: 140 }

  validates :description,
  presence: true, length: { minimum: 20, maximum: 1000 }

  validates :price,
  presence: true, numericality: { only_integer: true, greater_than: 1, less_than: 1000 }

  validates :location,
  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send
  has_many :attendances, foreign_key: "noob", class_name: "Attendance"
  has_many :events, through: :attendances, foreign_key: "noob", class_name: "Attendance"
  has_many :events, foreign_key: "administrator", class_name: "Event"
  has_many :noobs, foreign_key: "noob_id", class_name: "Attendance"
  has_many :administrators, foreign_key: 'administrator_id', class_name: "Attendance"






  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_parameters, if: :devise_controller?

def configure_devise_parameters
  devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :is_alive, :email, :password, :password_confirmation)}
  devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :is_alive, :email, :password, :password_confirmation)}
end
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create
    current_user.avatar.attach(params[:avatar])
    redirect_to static_pages_secret_path
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = params[:price]
    @event = Event.find(params[:id])

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })

@event.noob << current_user
flash[:succes] = "Vous vous êtes inscrit à l'événement "
redirect_to event_path(@event.id)

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  before_action :authenticate_user!, only: [:show, :create, :destroy, :edit, :new, :update]
  def index
    @events = Event.all
  end

  def show
  @event = Event.find(params[:id])
  end

  def new

  end

  def create

start_date = (params[:start_date]+" "+params[:hour_date]+":00")
end_date = (params[:end_date]+" "+params[:hour_end]+":00")

    @event = Event.create(start_date: start_date, end_date: end_date, title: params[:title], description: params[:description], location: params[:location], price: params[:price], administrator: current_user )
    if @event.save
      if params[:avatar] != nil
      @event.avatar.attach(params[:avatar])
      end
    redirect_to event_path(@event.id)
    else
      flash.now[:notice] = "Vérifiez les informations que vous avez rentré, certaine ne rentre pas dans les critères. "
render "new"
    end
  end

  def destroy
  end

  def edit
  end

  def update
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  def index
  end

  def secret
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/event/index.html.erb
<% if user_signed_in? %>
<center> <h1> Bonjour <%= current_user.first_name %> </h1> </center>

        <% end %>

        <p><center><h3 ><strong> Vous voulez crée un évenement?</strong></h3> </center></p>
            <center><h5 ><a class ="btn btn-dark btn-primary"  <%= link_to "Crée un évènement", new_event_path %> </a></h5></center>



<div class="card-columns">
<% @events.each do |event| %>
<div class="card ">
  <% if event.avatar.attached? == false %>
  <img class="card-img-top  "   src="https://d.wildapricot.net/images/newsblog/bigstock-events-7444309.jpg" alt="Card image cap">
<% else %>
  <center><img class="card-img-top " style="weight: 100%" <%= image_tag event.avatar, alt: 'avatar' %></center>
  <% end %>
  <div class="card-body bg-light card-md ">
    <h5 class="card-title"><%= event.title %></h5>
    <p class="card-text"> Prix : <%= event.price %> euros </p>
    <p class="card-text"> <small class="text-muted"> Début de l'évènement : </small><%= event.start_date.day %> <%= event.start_date.strftime("%B") %>  <%= event.start_date.year %>  Début à   <%= event.start_date.hour %> h <%= event.start_date.strftime("%M")  %>  </p>
<p class="card-text"><small class="text-muted"> Fin de l'évènement : </small>  <%= event.end_date.day %> <%= event.end_date.strftime("%B") %>  <%= event.end_date.year %> Fin à   <%= event.end_date.hour %> h <%= event.end_date.strftime("%M")  %>  </p>
    <p class="card-text"><strong><%= event.location %></strong></p>
    <a class ="card-text btn btn-dark btn-primary"  <%= link_to "Voir l'évènement", event_path(event.id) %> </a>
    <% if event.noob.include? current_user %>
    <strong><small>       Vous participez à cet événement </small></strong>
    <% end %>
  </div>
</div>


<% end %>

</div>

app/views/event/new.html.erb
<div class="container bg-light ">
  <div class="row">
    <div class="col-md offset-md-1">
      <br><br><br>
      <%= form_tag url_for(controller: 'event',action: 'create', method: "post"), multipart: true do %>

        <h1 class="h3 mb-3 font-weight-normal text-center">Crée votre évènement</h1>
        <div class="form-group">
          <%= label_tag :title, "Titre" %>
<br/>
          <%= text_field_tag :title, @titre %>( 5 à 150 caractère)
        </div>


        <%= file_field_tag :avatar %>


        <div class="form-group">
          <%= label_tag :description, "Description de l'évènement" %>
<br/>
          <%= text_field_tag :description %>    ( minimum 20 caractère )
        </div>
  <br/>
        <div class="form-group">
          <%= label_tag :location, "Lieu de l'évènement" %><br />
          <br/>
          <%= text_field_tag :location %>
        </div>
  <br/>
        <div class="form-group">
          <%= label_tag :price, "Prix  " %> ( entre 1 et 1000 )
          <br/>
          <%= text_field_tag :price %>
          euros
        </div>
  <br/>
        <div class="form-group">
          <%= label_tag :price, "Début  " %>
          <br/>
          <%= date_field_tag :start_date %>
        </div>
  <br/>
        <div class="form-group">
          <%= label_tag :price, "A quel heure l'évènement commence?  " %>
          <br/>
          <%= time_field_tag :hour_date  %>
        </div>
<br/>
        <div class="form-group">
          <%= label_tag :end_date, "Fin  " %>
          <br/>
          <%= date_field_tag :end_date %>
        </div>
  <br/>
        <div class="form-group">
          <%= label_tag :price, "A quel heure l'évènement se finnis?  " %>
          <br/>
          <%= time_field_tag :hour_end  %>
        </div>


        <div class="actions mt-5">
          <%= submit_tag "Valider", class: "btn btn-lg btn-dark btn-block" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/event/show.html.erb
<center><div class="bg-light" style="width: 80%;" >
  <% if @event.avatar.attached? == false %>
  <img class="card-img-top  "  src="https://d.wildapricot.net/images/newsblog/bigstock-events-7444309.jpg" alt="Card image cap">
<% else %>
  <center><img class="card-img-top " <%= image_tag @event.avatar, alt: 'avatar' %></center>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><h1> <%= @event.title %> </h1></h5>
    <h3 class="card-text"><h3> <%= @event.description %> </h3>
    <h3>Début à : <%= @event.start_date %> </h3>
    <h3>Fin à : <%= @event.end_date %> </h3>
    <h3>Lieu : <%= @event.location %> </h3>
    <br/>
    <h3>Prix : <%= @event.price %> € </h3>
    <h3>Nombre de participant : <%= @event.noob.count %> </h3>
    <h3><small>Créateur de l'évent  : <%= @event.administrator.first_name %></small> </h3>
<% if @event.administrator == current_user %>

<% else %>
 <% if @event.noob.include? current_user %>
 <strong><h4 class='button btn-dark'> Vous êtes inscrit à l'évènement </h4></strong>
 <% else %>
    <%= form_tag charges_path do %>
      <article>
        <% if flash[:error].present? %>
          <div id="error_explanation">
            <p><%= flash[:error] %></p>
          </div>
        <% end %>
        <label class="amount">
          <span>Prix : <%= @event.price %> €</span>
        </label>
      </article>
      <%= hidden_field_tag 'id', @event.id %>
      <%= hidden_field_tag 'price', (@event.price * 100) %>

      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-description="Acheter un billet pour l'évènement"
              data-amount="<%= @event.price * 100 %>"
              data-currency="eur"
              data-locale="auto"></script>
    <% end %>
<% end %>
<% end %>
  </div>
</div>
<% if current_user == @event.administrator %>
<h3> Liste des participant </h3>
<div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    <% @event.noob.each do |noob| %>
    <li class="list-group-item"><%= noob.first_name %>  <%= noob.last_name %></li>
      </ul>
<% end %>

</div>
<% end %>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorldEvent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

<center>  <a class=" dropdown-item text-white bg-dark "  <%= link_to "World Event 42", root_path %> </a> </center>

  <div class="text-white dropdown navbar-nav ml-auto mr-5  ">



      <% if user_signed_in? %>

          <a class="dropdown-item text-white bg-dark"  <%= link_to "Sign out", '/users/sign_out', method: :delete %> </a>





        <a class="dropdown-item text-white bg-dark"     <%= link_to "Mon profil", static_pages_secret_path %> </a>






      <% else %>
      <a class="dropdown-item text-white bg-dark" <%= link_to "Crée un compte", '/users/sign_up' %></a>
      <a class="dropdown-item text-white bg-dark" <%= link_to "Se connecter",'/users/sign_in' %></a>
      <% end %>

    </div></nav>

    <% if flash[:notice] %>
  <center>  <div class="alert alert-primary" role="alert">
  <%= flash[:notice] %>
</div></center>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
      Voici ton nom : <%= current_user.first_name %> 
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<html>
<body>



<center>
<%= form_tag user_avatars_path(current_user.id), multipart: true do %>
  <%= file_field_tag :avatar %>
  <%= submit_tag "Valider" %>
<% end %>
</center>
<% if current_user.avatar.attached? == false %>
<center>
<div class="card " style="width: 25rem;height: 30rem">
<%= image_tag  'https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png', alt: 'avatar' %>
<% else %>
 <center>
 <div class="card " style="width: 25rem;height: 30rem">
<%= image_tag current_user.avatar, alt: 'avatar' %>
<% end %>
<div class="card-body">


  <div class="  card bg-dark text-white  ">

    <h1><%= current_user.first_name %></h1>
    <p> <%=  current_user.last_name %> </p>
    <p>  <%=  current_user.email %> </p>
</div>
</div>
</div>

          <a class="dropdown-item text-dark bg-light"     <%= link_to "Edit email / password", edit_user_registration_path %> </a>
<center>

<br/>
<br/>
<h3><p class ="text-dark"> Voici vos évènement crée  : </p></h3>


      <div class="card-columns">
      <%  current_user.events.all.each do |event| %>
      <div class="card ">
        <% if event.avatar.attached? == false %>
        <img class="card-img-top  "   src="https://d.wildapricot.net/images/newsblog/bigstock-events-7444309.jpg" alt="Card image cap">
      <% else %>
        <center><img class="card-img-top " style="weight: 100%" <%= image_tag event.avatar, alt: 'avatar' %></center>
        <% end %>
        <div class="card-body bg-light card-md ">
          <h5 class="card-title"><%= event.title %></h5>
          <p class="card-text"> Prix : <%= event.price %> euros </p>
          <p class="card-text"> <small class="text-muted"> Début de l'évènement : </small><%= event.start_date.day %> <%= event.start_date.strftime("%B") %>  <%= event.start_date.year %>  Début à   <%= event.start_date.hour %> h <%= event.start_date.strftime("%M")  %>  </p>
      <p class="card-text"><small class="text-muted"> Fin de l'évènement : </small>  <%= event.end_date.day %> <%= event.end_date.strftime("%B") %>  <%= event.end_date.year %> Fin à   <%= event.end_date.hour %> h <%= event.end_date.strftime("%M")  %>  </p>
          <p class="card-text"><strong><%= event.location %></strong></p>
          <a class ="card-text btn btn-dark btn-primary"  <%= link_to "Voir l'évènement", event_path(event.id) %> </a>
          <% if event.noob.include? current_user %>
          <strong><small>       Vous participez à cet événement </small></strong>
          <% end %>
        </div>
      </div>


      <% end %>

      </div>
</body>

app/views/user/show.html.erb
<h1> Voila </h1>